[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yaradb-client"
version = "0.1.1"
authors = [
    { name = "Tymofii Shchur", email = "tymofiischur@gmail.com" },
]
description = "Official Python-client for YaraDB."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Database",
]
dependencies = [
    "requests>=2.20.0"
]

[project.urls]
Homepage = "https://github.com/illusiOxd/yaradb-client-py"
"Bug Tracker" = "https://github.com/illusiOxd/yaradb-client-py/issues"
"Source" = "https://github.com/illusiOxd/yaradb"